In [2]:
import numpy as np

arr = np.array([1, 2, 3, 4])

print(arr[0])

1


Access 2-D Arrays

In [3]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('2nd element on 1st row: ', arr[0, 1])

2nd element on 1st row:  2


Access 3-D Arrays
To access elements from 3-D arrays we can use comma separated integers representing the dimensions and the index of the element.

In [4]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

print(arr[0, 1, 2])

6


Use negative indexing to access an array from the end.

In [5]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('Last element from 2nd dim: ', arr[1, -1])

Last element from 2nd dim:  10


We pass slice instead of index like this: [start:end].

We can also define the step, like this: [start:end:step].

In [6]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5])

[2 3 4 5]


In [7]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[-3:-1])

[5 6]


Slicing 2-D Arrays

In [8]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[1, 1:4])

[7 8 9]


In [9]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[0:2, 2])

[3 8]


In [10]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[0:2, 1:4])

[[2 3 4]
 [7 8 9]]


In [11]:
!git add .

In [12]:
!git commit -m "Array splicing and indexing completed"

[main 81b35a9] Array splicing and indexing completed
 5 files changed, 672 insertions(+), 27 deletions(-)
 rename NumPy/.ipynb_checkpoints/{Untitled-checkpoint.ipynb => array_indexing-checkpoint.ipynb} (100%)
 delete mode 100644 NumPy/Untitled.ipynb
 create mode 100644 NumPy/array_indexing.ipynb


In [13]:
!git push

To https://github.com/Bhavishya007-bit/Python-Data-Science.git
   804e6a6..81b35a9  main -> main
