In [1]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr)

[1 2 3 4 5]


In [2]:
print(np.__version__)

2.2.1


In [3]:
print(type(arr))

<class 'numpy.ndarray'>


To create an ndarray, we can pass a list, tuple or any array-like object into the array() method, and it will be converted into an ndarray:

In [4]:
arr = np.array((1, 2, 3, 4, 5))

print(arr)

[1 2 3 4 5]


0-D arrays, or Scalars, are the elements in an array. Each value in an array is a 0-D array.

In [5]:
arr = np.array(42)

print(arr)

42


An array that has 0-D arrays as its elements is called uni-dimensional or 1-D array.

These are the most common and basic arrays.

In [6]:
arr = np.array([1, 2, 3, 4, 5])

print(arr)

[1 2 3 4 5]


An array that has 1-D arrays as its elements is called a 2-D array.

These are often used to represent matrix or 2nd order tensors.

NumPy has a whole sub module dedicated towards matrix operations called numpy.mat

In [8]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

print(arr)

[[1 2 3]
 [4 5 6]]


An array that has 2-D arrays (matrices) as its elements is called 3-D array.

These are often used to represent a 3rd order tensor.

In [9]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(arr)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


NumPy Arrays provides the ndim attribute that returns an integer that tells us how many dimensions the array have.

In [10]:
a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


An array can have any number of dimensions.

When the array is created, you can define the number of dimensions by using the ndmin argument.

In [13]:
arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('number of dimensions :', arr.ndim)

[[[[[1 2 3 4]]]]]
number of dimensions : 5


In [14]:
!git add .

In [15]:
!git commit -m "Array creation completed"

[main 804e6a6] Array creation completed
 4 files changed, 331 insertions(+)
 create mode 100644 NumPy/.ipynb_checkpoints/Untitled-checkpoint.ipynb
 create mode 100644 NumPy/.ipynb_checkpoints/creating_arrays-checkpoint.ipynb
 create mode 100644 NumPy/Untitled.ipynb
 create mode 100644 NumPy/creating_arrays.ipynb


In [16]:
!git push

To https://github.com/Bhavishya007-bit/Python-Data-Science.git
   9ee9d01..804e6a6  main -> main
